apiVersion: apps/v1
kind: Deployment
metadata:
  name: openscore-core
  namespace: openscore
spec:
  template:
    spec:
      containers:
        - name: core
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: jdbc_url
            - name: QUARKUS_MAILER_FROM
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: from
            - name: QUARKUS_MAILER_HOST
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: host
            - name: QUARKUS_MAILER_PORT
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: port
            - name: QUARKUS_MAILER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: username
            - name: QUARKUS_MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: password
            - name: OPENSCORE_MAIL_RECOVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: recover_url
            - name: OPENSCORE_MAIL_WELCOME_URL
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: welcome_url
