overrides:
  '@hono/node-server': '>=1.19.13'
  postcss: '>=8.5.10'

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
