pipeline {
    agent {
        label "nodejs"
    }
    options { 
        skipDefaultCheckout() 
    }
    stages {
        stage("Checkout") {
            steps {
                git branch: env.BRANCH, url: env.REPO
            }
        }
        stage("Build") {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject("openscore") {
                            sh  "npm install"
                            sh  "./node_modules/@angular/cli/bin/ng build --prod --aot"

                            if (!openshift.selector("bc", "openscore-core").exists()) {
                                // Creates the application if not exists
                                openshift.newBuild("httpd:2.4", "--binary", "--name=openscore-ui");                  
                            } else {
                                // Starts a new build and waits for its completion
                                openshift.selector("bc", "openscore-uicore").startBuild("--from-dir=./dist"), "--wait=true");
                            }
                        }
                    }
                }
            }
        }
        stage("Deploy") {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject("openscore") {
                            if (!openshift.selector("dc", "openscore-ui").exists()) {
                                createApp("openscore-ui", "latest");                   
                            } else {
                                // Rollouts to latest version
                                openshift.selector("dc", "openscore-ui").rollout().latest();   
                            }          
                        }
                    }
                }
            }
        }      
    }
}

def createApp(app, tag) {
    // Creates the application and get the brand new BuildConfig
    def dc = openshift.newApp("${app}:${tag}").narrow("dc");
    // Creates the app Route
    openshift.selector("svc", app).expose();

    // Waits for the deployment to finish
    while (dc.object().spec.replicas != dc.object().status.availableReplicas) {
        sleep 10
    }
    
    // Removes the triggers  
    openshift.set("triggers", "dc/${app}", "--manual");
}