apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openscore-issuer
  namespace: openscore
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: openscore-issuer-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
