global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    app: openscore-ng
    env: production

scrape_configs:
  - job_name: openscore-ng
    scheme: https
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - rhopenscore.com
        labels:
          instance: rhopenscore.com
