allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
storeDir: /Users/aparedes/Library/pnpm/store/v11
