apiVersion: apps/v1
kind: Deployment
metadata:
  name: openscore-ui
  namespace: openscore
spec:
  selector:
    matchLabels:
      app: openscore-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: openscore-ui
    spec:
      containers:
      - name: core
        image: registry.digitalocean.com/openscore/openscore-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openscore-ui
  namespace: openscore
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openscore-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openscore-ui
spec:
  rules:
    - host: rhopenscore.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openscore-ui
                port:
                  number: 80
