apiVersion: apps/v1
kind: Deployment
metadata:
  name: openscore-core
  namespace: openscore
spec:
  selector:
    matchLabels:
      app: openscore-core
  replicas: 1
  template:
    metadata:
      labels:
        app: openscore-core
    spec:
      containers:
      - name: core
        image: registry.digitalocean.com/openscore/openscore-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: openscore-core
  namespace: openscore
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: openscore-core
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openscore-core
spec:
  rules:
    - host: rhopenscore.com
      http:
        paths:
          - path: /openscore/api/rest
            pathType: Prefix
            backend:
              service:
                name: openscore-core
                port: 
                  number: 8080    