apiVersion: apps/v1
kind: Deployment
metadata:
  name: openscore-ui
  namespace: openscore
spec:
  template:
    spec:
      containers:
        - name: ui
          image: localhost:5000/openscore/openscore-ui:latest